# Generated by Django 6.0.4 on 2026-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='gas_brand',
            field=models.CharField(choices=[('Litro', 'Litro'), ('Laugfs', 'Laugfs'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
