# Generated by Django 6.0.4 on 2026-05-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cylinder_gas_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_method',
            field=models.CharField(choices=[('Delivery', 'Home Delivery'), ('Pickup', 'Store Pickup')], default='Pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card Payment'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
    ]
