# Generated by Django 6.0.4 on 2026-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_contact_number_booking_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
